### PR TITLE
Feature/fixes

### PR DESCRIPTION
**Pull request by arfbtwn**
Various fixes, some refactoring and the Mono.Posix build reference update

### CODE REVIEW

**Comment by Carbenium** [comment]
Ah damn. I thought you could review single commits... I only reviewed 033e1aab50e490eadfb6dc2851d86698e6968df8
Life is a bit busy right now...

**Comment by arfbtwn** [comment]
No problem, I just had a bit of a binge this weekend and pushed out some rebased branches (sorry for that) to try and slim down the feature/lite branch into just its required commits for the new UI (same for the Hyena repo)

This will sit for a bit and I'll take another look at it later, especially 9d952b3 that really needs splitting in two.

**Comment by Carbenium** [comment]
@arfbtwn Any chance we could get cb0d2e5 and a41bb41 into master? I think it would make my life a bit easier to base the notification library work directly on those.

**Comment by arfbtwn** [comment]
cb0d2e5 needs a bit more work - skills wise I'm okay, I just need to finish mapping the dependencies and automatically enabling extensions/other features. As it is it's great for build scripts that pass all the use/with flags but otherwise the user ends up with a very minimal build.

a41bb41 - sure thing :+1:

yeah, ff05591 is a good candidate - I'll push a feature/bugs branch and start cherry-picking choice patches into there.

**Comment by arfbtwn** [comment]
Shame, GH is doing some magic again, some of these commits are already in master - it really doesn't agree with my re-ordering of commit history 😆 

I'll do my best to improve f51e4c2 and 0e8bec0 - after that we should have an awesome auto-tools build system and all that'll be left here will be little bug fixes in a decent order.

**Comment by arfbtwn** [comment]
Remaining commits decomposed into: #41 & #42

**Pull request closed without merging**
