### PR TITLE
Feature/bugs

### LINKED ISSUE #49: browser: Initially Empty
The filter widgets are empty at program start and need toggling for items to show.

### PR DESCRIPTION
**Pull request by arfbtwn**
Resolves #49, @nicman23 can you confirm if you've seen that issue and if so, whether this resolves it for you or has any other unwanted effects?

### CODE REVIEW

**Comment by nicman23** [comment]
sure, anything in particular ?

**Comment by nicman23** [comment]
can you please fix some compiling errors when compiling with gtk2 and gtk3 libs in system ie:

```
MCS   ../../../bin/Banshee.Dap.AppleDevice.dll
error CS1703: An assembly `atk-sharp' with the same identity has already been imported. Consider removing one of the references
/usr/lib/pkgconfig/../../lib/mono/gtk-sharp-2.0/atk-sharp.dll (Location of the symbol related to previous error)
/usr/lib/pkgconfig/../../lib/mono/gtk-sharp-3.0/atk-sharp.dll (Location of the symbol related to previous error)
error CS1703: An assembly `gdk-sharp' with the same identity has already been imported. Consider removing one of the references
/usr/lib/pkgconfig/../../lib/mono/gtk-sharp-2.0/gdk-sharp.dll (Location of the symbol related to previous error)
/usr/lib/pkgconfig/../../lib/mono/gtk-sharp-3.0/gdk-sharp.dll (Location of the symbol related to previous error)
error CS1703: An assembly `glib-sharp' with the same identity has already been imported. Consider removing one of the references
/usr/lib/pkgconfig/../../lib/mono/gtk-sharp-2.0/glib-sharp.dll (Location of the symbol related to previous error)
/usr/lib/pkgconfig/../../lib/mono/gtk-sharp-3.0/glib-sharp.dll (Location of the symbol related to previous error)
error CS1703: An assembly `gtk-sharp' with the same identity has already been imported. Consider removing one of the references
/usr/lib/pkgconfig/../../lib/mono/gtk-sharp-2.0/gtk-sharp.dll (Location of the symbol related to previous error)
/usr/lib/pkgconfig/../../lib/mono/gtk-sharp-3.0/gtk-sharp.dll (Location of the symbol related to previous error)
error CS1703: An assembly `pango-sharp' with the same identity has already been imported. Consider removing one of the references
/usr/lib/pkgconfig/../../lib/mono/gtk-sharp-2.0/pango-sharp.dll (Location of the symbol related to previous error)
/usr/lib/pkgconfig/../../lib/mono/gtk-sharp-3.0/pango-sharp.dll (Location of the symbol related to previous error)
```

**Comment by arfbtwn** [comment]
specifically the issue I logged in #49 - empty browser when you first open the program or enable the setting.

**Comment by nicman23** [comment]
* not opening a new issue just because i am not sure if it is a bug but with --disable-gst_sharp, --enable-gst-native is not assumed! so you end up with a music player that cannot play music :P

* genre browser is empty no matter what i do

**Comment by arfbtwn** [comment]
Yeah I noticed the blank genre browser too - I'll take a look, cheers :+1:

**Comment by nicman23** [comment]
also in media panel on the albums i cannot scroll

**Comment by arfbtwn** [comment]
I just tested it and I can scroll okay, any reproduction steps for that?

**Comment by nicman23** [comment]
.... i do not know what to tell you... the only relevant info is that i use libinput.

tested on whell, touchpad and trackpoint..

if i resize the window then it works. On opening the window the whole album browser seems squeezed together

before resize

screenshot_20171008_140751


after resize

screenshot_20171008_140839

**Comment by arfbtwn** [comment]
pretty sure I've seen that behaviour when using the album browser in the regular program window, would you raise it as a separate issue please?

**Comment by nicman23** [comment]
for #49 no sorry never had it.

**Pull request merged**
